// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.3
// source: internal/network/proto/protocol.proto

package proto

import (
	context "context"
	proto "github.com/cjc7373/bitcoin_go/internal/block/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Bitcoin_SendNodes_FullMethodName         = "/Bitcoin/SendNodes"
	Bitcoin_SendChainMetadata_FullMethodName = "/Bitcoin/SendChainMetadata"
)

// BitcoinClient is the client API for Bitcoin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BitcoinClient interface {
	SendNodes(ctx context.Context, in *Nodes, opts ...grpc.CallOption) (*Empty, error)
	// chain metadata will be broadcasted when a new block is mined
	SendChainMetadata(ctx context.Context, in *proto.Blockchain, opts ...grpc.CallOption) (*Empty, error)
}

type bitcoinClient struct {
	cc grpc.ClientConnInterface
}

func NewBitcoinClient(cc grpc.ClientConnInterface) BitcoinClient {
	return &bitcoinClient{cc}
}

func (c *bitcoinClient) SendNodes(ctx context.Context, in *Nodes, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Bitcoin_SendNodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bitcoinClient) SendChainMetadata(ctx context.Context, in *proto.Blockchain, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Bitcoin_SendChainMetadata_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BitcoinServer is the server API for Bitcoin service.
// All implementations must embed UnimplementedBitcoinServer
// for forward compatibility
type BitcoinServer interface {
	SendNodes(context.Context, *Nodes) (*Empty, error)
	// chain metadata will be broadcasted when a new block is mined
	SendChainMetadata(context.Context, *proto.Blockchain) (*Empty, error)
	mustEmbedUnimplementedBitcoinServer()
}

// UnimplementedBitcoinServer must be embedded to have forward compatible implementations.
type UnimplementedBitcoinServer struct {
}

func (UnimplementedBitcoinServer) SendNodes(context.Context, *Nodes) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNodes not implemented")
}
func (UnimplementedBitcoinServer) SendChainMetadata(context.Context, *proto.Blockchain) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendChainMetadata not implemented")
}
func (UnimplementedBitcoinServer) mustEmbedUnimplementedBitcoinServer() {}

// UnsafeBitcoinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BitcoinServer will
// result in compilation errors.
type UnsafeBitcoinServer interface {
	mustEmbedUnimplementedBitcoinServer()
}

func RegisterBitcoinServer(s grpc.ServiceRegistrar, srv BitcoinServer) {
	s.RegisterService(&Bitcoin_ServiceDesc, srv)
}

func _Bitcoin_SendNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nodes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitcoinServer).SendNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bitcoin_SendNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitcoinServer).SendNodes(ctx, req.(*Nodes))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bitcoin_SendChainMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.Blockchain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitcoinServer).SendChainMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bitcoin_SendChainMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitcoinServer).SendChainMetadata(ctx, req.(*proto.Blockchain))
	}
	return interceptor(ctx, in, info, handler)
}

// Bitcoin_ServiceDesc is the grpc.ServiceDesc for Bitcoin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bitcoin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Bitcoin",
	HandlerType: (*BitcoinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNodes",
			Handler:    _Bitcoin_SendNodes_Handler,
		},
		{
			MethodName: "SendChainMetadata",
			Handler:    _Bitcoin_SendChainMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/network/proto/protocol.proto",
}
