// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: internal/network/proto/protocol.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Bitcoin_RequestNodes_FullMethodName   = "/Bitcoin/RequestNodes"
	Bitcoin_BroadcastNodes_FullMethodName = "/Bitcoin/BroadcastNodes"
)

// BitcoinClient is the client API for Bitcoin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BitcoinClient interface {
	RequestNodes(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Empty, error)
	BroadcastNodes(ctx context.Context, in *NodeBroadcast, opts ...grpc.CallOption) (*Empty, error)
}

type bitcoinClient struct {
	cc grpc.ClientConnInterface
}

func NewBitcoinClient(cc grpc.ClientConnInterface) BitcoinClient {
	return &bitcoinClient{cc}
}

func (c *bitcoinClient) RequestNodes(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Bitcoin_RequestNodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bitcoinClient) BroadcastNodes(ctx context.Context, in *NodeBroadcast, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Bitcoin_BroadcastNodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BitcoinServer is the server API for Bitcoin service.
// All implementations must embed UnimplementedBitcoinServer
// for forward compatibility
type BitcoinServer interface {
	RequestNodes(context.Context, *Node) (*Empty, error)
	BroadcastNodes(context.Context, *NodeBroadcast) (*Empty, error)
	mustEmbedUnimplementedBitcoinServer()
}

// UnimplementedBitcoinServer must be embedded to have forward compatible implementations.
type UnimplementedBitcoinServer struct {
}

func (UnimplementedBitcoinServer) RequestNodes(context.Context, *Node) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestNodes not implemented")
}
func (UnimplementedBitcoinServer) BroadcastNodes(context.Context, *NodeBroadcast) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastNodes not implemented")
}
func (UnimplementedBitcoinServer) mustEmbedUnimplementedBitcoinServer() {}

// UnsafeBitcoinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BitcoinServer will
// result in compilation errors.
type UnsafeBitcoinServer interface {
	mustEmbedUnimplementedBitcoinServer()
}

func RegisterBitcoinServer(s grpc.ServiceRegistrar, srv BitcoinServer) {
	s.RegisterService(&Bitcoin_ServiceDesc, srv)
}

func _Bitcoin_RequestNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitcoinServer).RequestNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bitcoin_RequestNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitcoinServer).RequestNodes(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bitcoin_BroadcastNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeBroadcast)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitcoinServer).BroadcastNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bitcoin_BroadcastNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitcoinServer).BroadcastNodes(ctx, req.(*NodeBroadcast))
	}
	return interceptor(ctx, in, info, handler)
}

// Bitcoin_ServiceDesc is the grpc.ServiceDesc for Bitcoin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bitcoin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Bitcoin",
	HandlerType: (*BitcoinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestNodes",
			Handler:    _Bitcoin_RequestNodes_Handler,
		},
		{
			MethodName: "BroadcastNodes",
			Handler:    _Bitcoin_BroadcastNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/network/proto/protocol.proto",
}
