// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.27.3
// source: internal/block/proto/chainstate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UTXO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction []byte `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	OutputIndex int32  `protobuf:"varint,2,opt,name=output_index,json=outputIndex,proto3" json:"output_index,omitempty"`
}

func (x *UTXO) Reset() {
	*x = UTXO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_block_proto_chainstate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UTXO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTXO) ProtoMessage() {}

func (x *UTXO) ProtoReflect() protoreflect.Message {
	mi := &file_internal_block_proto_chainstate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTXO.ProtoReflect.Descriptor instead.
func (*UTXO) Descriptor() ([]byte, []int) {
	return file_internal_block_proto_chainstate_proto_rawDescGZIP(), []int{0}
}

func (x *UTXO) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *UTXO) GetOutputIndex() int32 {
	if x != nil {
		return x.OutputIndex
	}
	return 0
}

type UTXOSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UTXOs []*UTXO `protobuf:"bytes,1,rep,name=UTXOs,proto3" json:"UTXOs,omitempty"`
}

func (x *UTXOSet) Reset() {
	*x = UTXOSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_block_proto_chainstate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UTXOSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTXOSet) ProtoMessage() {}

func (x *UTXOSet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_block_proto_chainstate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTXOSet.ProtoReflect.Descriptor instead.
func (*UTXOSet) Descriptor() ([]byte, []int) {
	return file_internal_block_proto_chainstate_proto_rawDescGZIP(), []int{1}
}

func (x *UTXOSet) GetUTXOs() []*UTXO {
	if x != nil {
		return x.UTXOs
	}
	return nil
}

var File_internal_block_proto_chainstate_proto protoreflect.FileDescriptor

var file_internal_block_proto_chainstate_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x04, 0x55, 0x54, 0x58, 0x4f, 0x12,
	0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x22, 0x26, 0x0a, 0x07, 0x55, 0x54, 0x58, 0x4f, 0x53, 0x65, 0x74, 0x12,
	0x1b, 0x0a, 0x05, 0x55, 0x54, 0x58, 0x4f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x55, 0x54, 0x58, 0x4f, 0x52, 0x05, 0x55, 0x54, 0x58, 0x4f, 0x73, 0x42, 0x34, 0x5a, 0x32,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6a, 0x63, 0x37, 0x33,
	0x37, 0x33, 0x2f, 0x62, 0x69, 0x74, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x67, 0x6f, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_block_proto_chainstate_proto_rawDescOnce sync.Once
	file_internal_block_proto_chainstate_proto_rawDescData = file_internal_block_proto_chainstate_proto_rawDesc
)

func file_internal_block_proto_chainstate_proto_rawDescGZIP() []byte {
	file_internal_block_proto_chainstate_proto_rawDescOnce.Do(func() {
		file_internal_block_proto_chainstate_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_block_proto_chainstate_proto_rawDescData)
	})
	return file_internal_block_proto_chainstate_proto_rawDescData
}

var file_internal_block_proto_chainstate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_block_proto_chainstate_proto_goTypes = []interface{}{
	(*UTXO)(nil),    // 0: UTXO
	(*UTXOSet)(nil), // 1: UTXOSet
}
var file_internal_block_proto_chainstate_proto_depIdxs = []int32{
	0, // 0: UTXOSet.UTXOs:type_name -> UTXO
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_block_proto_chainstate_proto_init() }
func file_internal_block_proto_chainstate_proto_init() {
	if File_internal_block_proto_chainstate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_block_proto_chainstate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UTXO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_block_proto_chainstate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UTXOSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_block_proto_chainstate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_block_proto_chainstate_proto_goTypes,
		DependencyIndexes: file_internal_block_proto_chainstate_proto_depIdxs,
		MessageInfos:      file_internal_block_proto_chainstate_proto_msgTypes,
	}.Build()
	File_internal_block_proto_chainstate_proto = out.File
	file_internal_block_proto_chainstate_proto_rawDesc = nil
	file_internal_block_proto_chainstate_proto_goTypes = nil
	file_internal_block_proto_chainstate_proto_depIdxs = nil
}
